version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.Dansoftowner:jSystemThemeDetector"
        versions: ["*"]
