version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.github.Dansoftowner:jSystemThemeDetector" # Nom complet de la dépendance
        versions: [">3.7"]
