name: Build and Release Compose Desktop App with JetBrains JDK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JetBrains JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.12'

      - name: Build with Gradle
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Linux artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: kmplog-client/build/compose/binaries/main/deb/*.deb

      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: kmplog-client/build/compose/binaries/main/dmg/*.dmg

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: kmplog-client/build/compose/binaries/main/msi/*.msi

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # nécessaire pour publier sur GitHub Release

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-deb

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-dmg

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-msi

      - name: Check downloaded artifacts
        run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux-deb/*
            macos-dmg/*
            windows-msi/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
